# Generated by Django 3.2.9 on 2022-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcraft_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtokenmodel',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jwtmodel',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jwtmodel',
            name='refresh_token',
            field=models.TextField(),
        ),
    ]
