from enum import IntEnum


class AuthRelatedErrorCodes(IntEnum):
    ACCESS_TOKEN_IS_IN_BLACK_LIST = 551
    INVALID_ACCESS_TOKEN = 552

    INVALID_FIREBASE_TOKEN = 558
    UNAUTHORIZED_AUTH_PROVIDER = 555

    INVALID_REFRESH_TOKEN = 560
    FAILED_TO_SEND_EMAIL = 561
