from enum import IntEnum


class AuthRelatedErrorCodes(IntEnum):
    INVALID_CREDENTIALS = 551
    ACCESS_TOKEN_IS_IN_BLACK_LIST = 552
    INVALID_ACCESS_TOKEN = 553
    INVALID_REFRESH_TOKEN = 554

    FAILED_TO_SEND_EMAIL = 555
    TOO_FREQUENT_ATTEMPTS = 556

    # UNAUTHORIZED_AUTH_PROVIDER = 555
